### ISSUE TITLE
Error while installing stubs

### ISSUE THREAD

**Issue by salvob41** [kwn/php-rdkafka-stubs#5]
After `php composer' of the composer json
this is the error. 
Any idea why this happens?

```Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for kwn/php-rdkafka-stubs ^0.0.4 -> satisfiable by kwn/php-rdkafka-stubs[0.0.4].
    - kwn/php-rdkafka-stubs 0.0.4 requires ext-rdkafka ^0.9.1 -> the requested PHP extension rdkafka has the wrong version (2.0.1) installed.

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/7.1/php.ini
    - /usr/local/etc/php/7.1/conf.d/ext-rdkafka.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.```

**Comment by kwn** [comment]
Hi @salvob41 

Thanks for reporting this issue.

It's because there's a constraint for rdkafka extension version in stubs repository. They work fine with rdkafka 0.9.1 and you're using rdkafka 2.0.1.

I'll review and update my stubs accordingly to make them working with ext-rdkafka 2.0.1 soon (hopefully this week).

**Comment by kwn** [comment]
@salvob41 

Hi there! Try again with php-rdkafka-stubs version 1.0.0. I've upgraded stubs to follow the most recent version of rdkafka (3.0.0).
